version: "3.9"
services:
  smtp4dev:
    image: rnwood/smtp4dev:v3
    restart: always
    ports:
      - "5000:80"
      - "25:25"
      - "143:143"
    volumes:
      - "./tmp/smtp4dev:/smtp4dev"
    environment:
      - ServerOptions__HostName=smtp4dev
